image: node:latest # change to match your node version

cache:
  paths:
    - node_modules/

before_script:
  - cd public
  - npm install

pages:
  stage: deploy
  script:
    - CI=false npm run build  # inside public . Has a public folder
    - rm -rf public  #inside public, removed public folder
    - cd .. #outside public, inside project root
    - mkdir frontend #inside project root
    - mv public/build frontend #inside project root
    - rm -rf public  #inside project root
    - mv frontend public

  artifacts:
    paths:
      - public # GitLab pages serve from a 'frontend' directory IT HAS TO BE PUBLIC: https://forum.gitlab.com/t/my-pipeline-always-failed-due-to-a-ghost-job-no-entries-extracted/24798/2
  
  only:
    - dev # run on dev branch